export const MODEL_REFERENCE_TEMPERATURE_C = 20;
export const MODEL_TEMPERATURE_STEP_C = 10;
export const LONG_FERMENTATION_BASE_COEFFICIENT = 14.5;
export const LONG_FERMENTATION_TIME_EXPONENT = -0.89;

export const SHORT_TIME_BLEND_END_HOURS = 12;
export const SHORT_TIME_BLEND_WINDOW_HOURS = 8;
export const SHORT_TIME_BOOST_MAX = 1.37;
export const SHORT_TIME_BOOST_EXPONENT = 1.35;

export const EMPIRICAL_TEMPERATURE_RANGE_C = {
  min: 16,
  max: 36,
} as const;

export const EMPIRICAL_TIME_RANGE_HOURS = {
  min: 4,
  max: 24,
} as const;

export const PRACTICAL_ROUNDING_THRESHOLD_GRAMS = 1;
export const PRACTICAL_ROUNDING_DECIMALS_AT_OR_ABOVE_THRESHOLD = 2;
export const PRACTICAL_ROUNDING_DECIMALS_BELOW_THRESHOLD = 3;
